version: '3.1'
services:
  vpn:
    privileged: true
    build: .
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    #cap_add:
    #  - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - kernel.msgmnb=65536
      - kernel.msgmax=65536
      - kernel.shmmax=68719476736
      - kernel.shmall=4294967296
      - net.ipv4.ip_forward=1
      - net.ipv4.tcp_syncookies=1
      - net.ipv4.conf.all.accept_source_route=0
      - net.ipv4.conf.default.accept_source_route=0
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.default.accept_redirects=0
      - net.ipv4.conf.all.send_redirects=0
      - net.ipv4.conf.default.send_redirects=0
      - net.ipv4.conf.lo.send_redirects=0
      - net.ipv4.conf.eth0.send_redirects=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.lo.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.icmp_echo_ignore_broadcasts=1
      - net.ipv4.icmp_ignore_bogus_error_responses=1
      # - net.core.wmem_max=12582912
      # - net.core.rmem_max=12582912
      # - net.ipv4.tcp_rmem="10240 87380 12582912"
      # - net.ipv4.tcp_wmem="10240 87380 12582912"
    volumes:
      - /lib/modules:/lib/modules:ro
      - ${PWD}/etc/ppp/chap-secrets:/etc/ppp/chap-secrets
      - ${PWD}/etc/ipsec.d/passwd:/etc/ipsec.d/passwd
      - ${PWD}/etc/ipsec.secrets:/etc/ipsec.secrets
    networks:
      - network_frontend
    labels:
      - traefik.enable=false
networks:
  network_frontend:
    external: true
