version: '3.4'

services:
  wordpress:
    container_name: lacquerlabs
    image: lacquerlabs/service-wordpress:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '250M'
    restart: unless-stopped
    volumes:
      - ./wp-content:/var/www/html/wp-content
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - network_db
      - network_proxy
    ports:
      - 80
    labels:
      - traefik.docker.network=network_proxy
      - traefik.frontend.rule=Host:lacquerlabs.docker.localhost
      - traefik.port=80
      - traefik.backend.healthcheck.interval=30s
      - traefik.backend.healthcheck.path=/wp-content/index.php

networks:
  network_proxy:
    external: true
  network_db:
    external: true
